import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import '@radix-ui/themes/styles.css';
import { UserProvider } from '@auth0/nextjs-auth0/client'
import { Theme } from "@radix-ui/themes";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <UserProvider>
        <Theme>
          <body className={inter.className}>
            <Navbar />
            {children}
          </body>
        </Theme>

      </UserProvider>
    </html>
  );
}
